import EMICalculatorPage from '../features/FinancialTools/Components/EMICalculatorPage.tsx' 
import FDCalculatorPage from '../features/FinancialTools/Components/FDCalculatorPage.tsx'
import SIPCalculatorPage from '../features/FinancialTools/Components/SIPCalculatorPage.tsx'
import HomePage from '../features/Layout/Components/HomePage.tsx'
import FinToolsListHomeComponent from '../features/FinancialTools/Components/FinToolsHomePage.tsx'
import UnderProgress from './UnderProgress.tsx'
 

export const routeConfig = [
  {
    path: "/",
    element: <HomePage />,
  },
  {
    path: "/financial-calculators/fd-calculator",
    element: <FDCalculatorPage />,
  },
  {
    path: "/financial-calculators/sip-calculator",
    element: <SIPCalculatorPage />,
  },
  {
    path: "/financial-calculators/emi-calculator",
    element: <EMICalculatorPage />,
  },
 {path: "/financial-calculators/ppf-calculator",element: <UnderProgress featureName="PPF calculator" />},
{path: "/financial-calculators/swp-calculator",element: <UnderProgress featureName="SWP calculator" />},
{path: "/financial-calculators/gst-calculator",element: <UnderProgress featureName="GST calculator" />},
{path: "/financial-calculators/income-tax",element: <UnderProgress featureName="Income Tax Calculator" />},
{path: "/financial-calculators/compound-interest",element: <UnderProgress featureName="Compound Interest calculator" />},
{path: "/financial-calculators/simple-interest",element: <UnderProgress featureName="Simple Interest calculator" />},
{path: "/financial-calculators/gratuity",element: <UnderProgress featureName="Gratuity calculator" />},
{path: "/financial-calculators/hra-calculator",element: <UnderProgress featureName="HRA calculator" />},
{path: "/financial-calculators/nps-calculator",element: <UnderProgress featureName="NPS calculator" />},
{path: "/financial-calculators/cagr-calculator",element: <UnderProgress featureName="cagr calculator" />},
{path: "/financial-calculators/roi-calculator",element: <UnderProgress featureName="ROI calculator" />},
{path: "/financial-calculators/inflation",element: <UnderProgress featureName="Inflation calculator" />},
{path: "/financial-calculators/retirement",element: <UnderProgress featureName="Retirement calculator" />},
{path: "/financial-calculators/lump-sum",element: <UnderProgress featureName="lump sum calculator" />},
{path: "/financial-calculators/savings",element: <UnderProgress featureName="Savings calculator" />},
{path: "/financial-calculators/tds-calculator",element: <UnderProgress featureName="TDS calculator" />},
{path: "/financial-calculators/ctc-calculator",element: <UnderProgress featureName="CTC calculator" />},
{path: "/image-tools/background-remover",element: <UnderProgress featureName="Background Remover" />},
{path: "//image-tools/qr-code-generator",element: <UnderProgress featureName="QR Code Generator" />},
{path: "/image-tools/image-compressor",element: <UnderProgress featureName="Image compressor" />},
{path: "/image-tools/image-resizer",element: <UnderProgress featureName="Image resizer" />},
{path: "/image-tools/image-cropper",element: <UnderProgress featureName="Image cropper" />},
{path: "/image-tools/image-converter",element: <UnderProgress featureName="Image converter" />},
{path: "/image-tools/image-to-base64",element: <UnderProgress featureName="Image To Base64 Converter" />},
{path: "/image-tools/watermark",element: <UnderProgress featureName="Watermark generator" />},
{path: "/image-tools/grayscale",element: <UnderProgress featureName="grayscale" />},
{path: "/image-tools/color-picker",element: <UnderProgress featureName="Color Picker" />},
{path: "/image-tools/favicon-generator",element: <UnderProgress featureName="favicon generator" />},
{path: "/image-tools/rotate-flip",element: <UnderProgress featureName="Rotate flip" />},
{path: "/image-tools/svg-to-png",element: <UnderProgress featureName="svg to png converter" />},
{path: "/image-tools/qr-scanner",element: <UnderProgress featureName="qr scanner" />},
{path: "/pdf-tools/merge-pdf",element: <UnderProgress featureName="merge pdf" />},
{path: "/pdf-tools/split-pdf",element: <UnderProgress featureName="split pdf" />},
{path: "/pdf-tools/rotate-pdf",element: <UnderProgress featureName="rotate pdf" />},
{path: "/pdf-tools/jpg-to-pdf",element: <UnderProgress featureName="jpg to pdf" />},
{path: "/pdf-tools/unlock-pdf",element: <UnderProgress featureName="unlock pdf" />},
{path: "/pdf-tools/protect-pdf",element: <UnderProgress featureName="protect pdf" />},
{path: "/pdf-tools/watermark-pdf",element: <UnderProgress featureName="watermark" />},
{path: "/pdf-tools/page-numbers",element: <UnderProgress featureName="page numbers" />},
{path: "/pdf-tools/extract-pages",element: <UnderProgress featureName="extract pages" />},
{path: "/pdf-tools/reorder-pdf",element: <UnderProgress featureName="reorder pdf" />},
{path: "/dev-tools/json-formatter",element: <UnderProgress featureName="json formatter" />},    
{path: "/dev-tools/base64-encoder",element: <UnderProgress featureName="base64 encoder" />},
{path: "/dev-tools/password-generator",element: <UnderProgress featureName="password generator" />},
{path: "/dev-tools/url-encoder",element: <UnderProgress featureName="url encoder" />},
{path: "/dev-tools/uuid-generator",element: <UnderProgress featureName="Uuid generator" />},
{path: "/dev-tools/sha256",element: <UnderProgress featureName="sha256" />},
{path: "/dev-tools/md5",element: <UnderProgress featureName="md5" />},
{path: "/dev-tools/jwt-decoder",element: <UnderProgress featureName="jwt decoder" />},
{path: "/dev-tools/regex-tester",element: <UnderProgress featureName="regex tester" />},
{path: "/dev-tools/json-to-csv",element: <UnderProgress featureName="json to csv" />},
{path: "/dev-tools/css-minifier",element: <UnderProgress featureName="css minifier" />},
{path: "/dev-tools/color-picker",element: <UnderProgress featureName="color picker" />},
{path: "/dev-tools/meta-tag-generator",element: <UnderProgress featureName="meta tag generator" />},
{path: "/dev-tools/epoch-converter",element: <UnderProgress featureName="epoch converter" />},
{path: "/dev-tools/html-encoder",element: <UnderProgress featureName="html encoder" />},
{path: "/dev-tools/cron-parser",element: <UnderProgress featureName="cron parser" />},
{path: "/text-tools/word-counter",element: <UnderProgress featureName="word converter" />},
{path: "/text-tools/case-converter",element: <UnderProgress featureName="case converter" />},
{path: "/text-tools/lorem-ipsum",element: <UnderProgress featureName="lorem ipsum" />},
{path: "/text-tools/diff-checker",element: <UnderProgress featureName="diff checker" />},
{path: "/text-tools/remove-duplicates",element: <UnderProgress featureName="remove duplicates" />},
{path: "/text-tools/sort-lines",element: <UnderProgress featureName="sort lines" />},
{path: "/text-tools/reverse-text",element: <UnderProgress featureName="reverse text" />},
{path: "/text-tools/text-to-slug",element: <UnderProgress featureName="text to slug" />},
{path: "/text-tools/find-replace",element: <UnderProgress featureName="find replace" />},
{path: "/text-tools/extract-emails",element: <UnderProgress featureName="extract emails" />},
{path: "/text-tools/extract-urls",element: <UnderProgress featureName="extract urls" />},
{path: "/text-tools/reading-time",element: <UnderProgress featureName="reading time" />},
{path: "/text-tools/palindrome-checker",element: <UnderProgress featureName="palindrome checker" />},
{path: "/unit-converters/length",element: <UnderProgress featureName="length converter" />},
{path: "/unit-converters/weight",element: <UnderProgress featureName="weight converter" />},
{path: "/unit-converters/temperature",element: <UnderProgress featureName="temperature converter" />},
{path: "/unit-converters/data-storage",element: <UnderProgress featureName="data storage converter" />},
{path: "/unit-converters/area",element: <UnderProgress featureName="area converter" />},
{path: "/unit-converters/speed",element: <UnderProgress featureName="speed converter" />},
{path: "/unit-converters/volume",element: <UnderProgress featureName="volume converter" />},
{path: "/unit-converters/number-base",element: <UnderProgress featureName="number base converter" />},
{path: "/unit-converters/time",element: <UnderProgress featureName="time converter" />},
{path: "/unit-converters/cooking",element: <UnderProgress featureName="cooking converter" />},
{path: "/health-tools/bmi-calculator",element: <UnderProgress featureName="BMI calculator" />},
{path: "/health-tools/bmr-calculator",element: <UnderProgress featureName="BMR calculator" />},
{path: "/health-tools/calorie-calculator",element: <UnderProgress featureName="calorie calculator" />},
{path: "/health-tools/age-calculator",element: <UnderProgress featureName="age calculator" />},
{path: "/health-tools/water-intake",element: <UnderProgress featureName="water intake calculator" />},
{path: "/health-tools/ideal-weight",element: <UnderProgress featureName="ideal weight calculator" />},
{path: "/health-tools/body-fat",element: <UnderProgress featureName="body fat " />},
{path: "/health-tools/sleep-calculator",element: <UnderProgress featureName="sleep calculator" />},
{path: "/health-tools/macro-calculator",element: <UnderProgress featureName="macro calculator" />},
{path: "/health-tools/heart-rate-zones",element: <UnderProgress featureName="heart rate zones" />},
{path: "/math-tools/percentage-calculator",element: <UnderProgress featureName="percentage calculator" />},
{path: "/math-tools/scientific-calculator",element: <UnderProgress featureName="scientific calculator" />},
{path: "/math-tools/fraction-calculator",element: <UnderProgress featureName="fraction calculator" />},
{path: "/math-tools/standard-deviation",element: <UnderProgress featureName="standard deviation" />},
{path: "/math-tools/lcm-gcd",element: <UnderProgress featureName="lcm gcd" />},
{path: "/math-tools/quadratic",element: <UnderProgress featureName="quadratic" />},
{path: "/math-tools/triangle-calculator",element: <UnderProgress featureName="triangle calculator" />},
{path: "/math-tools/prime-checker",element: <UnderProgress featureName="prime checker" />},
{path: "/math-tools/random-number",element: <UnderProgress featureName="random number" />},
{path: "/math-tools/mean-median-mode",element: <UnderProgress featureName="mean median mode" />},
{path: "/security-tools/password-strength",element: <UnderProgress featureName="password strength" />},
{path: "/security-tools/sha256",element: <UnderProgress featureName="sha256" />},
{path: "/security-tools/sha1",element: <UnderProgress featureName="sha1" />},
{path: "/security-tools/md5",element: <UnderProgress featureName="md5" />},
{path: "/security-tools/jwt-decoder",element: <UnderProgress featureName="jwt decoder" />},
{path: "/security-tools/aes-encrypt",element: <UnderProgress featureName="aes encrypt" />},
{path: "/security-tools/text-to-binary",element: <UnderProgress featureName="text to binary" />},
{path: "/security-tools/caesar-cipher",element: <UnderProgress featureName="caesar cipher" />},
{path: "/security-tools/rot13",element: <UnderProgress featureName="rot13" />},
{path: "/date-tools/age-calculator",element: <UnderProgress featureName="Age calculator" />},
{path: "/date-tools/date-difference",element: <UnderProgress featureName="Date difference" />},
{path: "/date-tools/timezone-converter",element: <UnderProgress featureName="TimeZone converter" />},
{path: "/date-tools/countdown-timer",element: <UnderProgress featureName="Countdown Timer" />},
{path: "/date-tools/unix-timestamp",element: <UnderProgress featureName="Unix Timestamp" />},
{path: "/date-tools/business-days",element: <UnderProgress featureName="Business Days" />},
{path: "/date-tools/week-number",element: <UnderProgress featureName="Week Number" />},
{path: "/date-tools/world-clock",element: <UnderProgress featureName="World Clock" />},
{path: "/financial-calculators",element: <FinToolsListHomeComponent/>},
{path: "/image-tools",element: <UnderProgress featureName="Image Tools" />},
{path: "/pdf-tools",element: <UnderProgress featureName="Pdf Converter Tools " />},
{path: "/dev-tools",element: <UnderProgress featureName="Dev Tools" />},
{path: "/unit-converters",element: <UnderProgress featureName="Unit Converter Tools" />},
{path: "/health-tools",element: <UnderProgress featureName="Health Tools" />},
{path: "/math-tools",element: <UnderProgress featureName="Math Converter Tools" />},
{path: "/security-tools",element: <UnderProgress featureName="Security Tools" />},
{path: "/text-tools",element: <UnderProgress featureName="Text Converter Tools" />},
{path: "/date-tools",element: <UnderProgress featureName="Date Converter Tools" />},
];

 